-- -- =====================================================
-- -- 1. Helper function for updated_at triggers
-- -- =====================================================
-- CREATE OR REPLACE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--     NEW.updated_at = CURRENT_TIMESTAMP;
--     RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- =====================================================
-- -- 2. users table (core profile)
-- -- =====================================================
-- CREATE TABLE users (
--     employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     email VARCHAR(255) UNIQUE NOT NULL,
--     ph_no VARCHAR(20) UNIQUE,
--     batch SMALLINT NOT NULL CHECK (batch BETWEEN 1900 AND 2100),
--     role VARCHAR(20) NOT NULL CHECK (role IN ('candidate', 'recruiter')),
--     status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0, 1)), -- 0=inactive, 1=active
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE INDEX idx_users_email ON users(email);
-- CREATE INDEX idx_users_batch ON users(batch);
-- CREATE INDEX idx_users_role ON users(role);

-- CREATE TRIGGER trigger_update_users_updated_at
--     BEFORE UPDATE ON users
--     FOR EACH ROW
--     EXECUTE FUNCTION update_updated_at_column();

-- -- =====================================================
-- -- 3. templates table (email templates)
-- -- =====================================================
-- CREATE TABLE templates (
--     id SERIAL PRIMARY KEY,
--     name VARCHAR(255) UNIQUE NOT NULL,
--     subject VARCHAR(255) NOT NULL,
--     body TEXT NOT NULL,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TRIGGER trigger_update_templates_updated_at
--     BEFORE UPDATE ON templates
--     FOR EACH ROW
--     EXECUTE FUNCTION update_updated_at_column();

-- -- =====================================================
-- -- 4. hosp_list table (hospital list)
-- -- =====================================================
-- CREATE TABLE hosp_list (
--     id SERIAL PRIMARY KEY,
--     name TEXT NOT NULL,
--     address TEXT UNIQUE NOT NULL
-- );

-- -- =====================================================
-- -- 5. auth table (credentials) – now references employee_id
-- -- =====================================================
-- CREATE TABLE auth (
--     user_id INTEGER PRIMARY KEY REFERENCES users(employee_id) ON DELETE CASCADE,
--     password_hash TEXT NOT NULL,
--     failed_attempt SMALLINT NOT NULL DEFAULT 0,
--     last_login TIMESTAMPTZ,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
--     -- No updated_at – passwords are not updated via normal flow
-- );

-- -- =====================================================
-- -- 6. first_login table (OTP management) – references employee_id
-- -- =====================================================
-- CREATE TABLE first_login (
--     user_id INTEGER PRIMARY KEY REFERENCES users(employee_id) ON DELETE CASCADE,
--     otp VARCHAR(6) NOT NULL,
--     valid_until TIMESTAMPTZ NOT NULL,
--     new BOOLEAN NOT NULL DEFAULT TRUE,   -- TRUE = still pending, FALSE = completed
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE INDEX idx_first_login_valid_until ON first_login(valid_until);

-- CREATE TRIGGER trigger_update_first_login_updated_at
--     BEFORE UPDATE ON first_login
--     FOR EACH ROW
--     EXECUTE FUNCTION update_updated_at_column();

-- -- =====================================================
-- -- 7. email_logs table (audit of sent emails) – now links via user_id
-- -- =====================================================
-- CREATE TABLE email_logs (
--     id SERIAL PRIMARY KEY,
--     template_id INTEGER REFERENCES templates(id) ON DELETE SET NULL,
--     user_id INTEGER REFERENCES users(employee_id) ON DELETE SET NULL,  -- who sent/received (if user exists)
--     recipient_email VARCHAR(255) NOT NULL,     -- actual email used (preserved for archival)
--     subject VARCHAR(255) NOT NULL,
--     status VARCHAR(50) NOT NULL CHECK (status IN ('sent', 'failed', 'bounced', 'opened', 'clicked')),
--     error_message TEXT,
--     sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE INDEX idx_email_logs_user_id ON email_logs(user_id);
-- CREATE INDEX idx_email_logs_recipient_email ON email_logs(recipient_email);
-- CREATE INDEX idx_email_logs_template_id ON email_logs(template_id);
-- CREATE INDEX idx_email_logs_sent_at ON email_logs(sent_at);
-- CREATE INDEX idx_email_logs_status ON email_logs(status);

-- -- =====================================================
-- -- 8. dox table (document tracking) – references employee_id
-- -- =====================================================
-- CREATE TABLE dox (
--     user_id INTEGER PRIMARY KEY REFERENCES users(employee_id) ON DELETE CASCADE,

--     -- Medical Exam
--     medical_status VARCHAR(20) NOT NULL DEFAULT 'pending' 
--         CHECK (medical_status IN ('pending', 'completed', 'rejected')),
--     medical_reason TEXT,
--     medical_file_path TEXT,
--     medical_original_filename TEXT,
--     medical_file_size INTEGER 
--         CHECK (medical_file_size IS NULL OR medical_file_size <= 10485760), -- 10 MB
--     medical_uploaded_at TIMESTAMPTZ,

--     -- Police Verification
--     police_status VARCHAR(20) NOT NULL DEFAULT 'pending' 
--         CHECK (police_status IN ('pending', 'completed', 'rejected')),
--     police_reason TEXT,
--     police_file_path TEXT,
--     police_original_filename TEXT,
--     police_file_size INTEGER 
--         CHECK (police_file_size IS NULL OR police_file_size <= 10485760),
--     police_uploaded_at TIMESTAMPTZ,

--     -- Final Clearance (status only)
--     final_status VARCHAR(20) NOT NULL DEFAULT 'pending' 
--         CHECK (final_status IN ('pending', 'completed', 'rejected')),
--     final_reason TEXT,

--     -- Joining Letter (status only)
--     joining_status VARCHAR(20) NOT NULL DEFAULT 'pending' 
--         CHECK (joining_status IN ('pending', 'completed', 'rejected')),
--     joining_reason TEXT,

--     -- Global flag: if true, user is allowed to upload/replace documents
--     upload_allowed BOOLEAN NOT NULL DEFAULT TRUE
-- );

-- CREATE INDEX idx_dox_medical_uploaded_at ON dox(medical_uploaded_at);
-- CREATE INDEX idx_dox_police_uploaded_at ON dox(police_uploaded_at);

-- -- =====================================================
-- -- 9. notifications table (for recruiter alerts)
-- -- =====================================================
-- CREATE TABLE notifications (
--     id SERIAL PRIMARY KEY,
--     message TEXT NOT NULL,
--     type VARCHAR(50) NOT NULL DEFAULT 'document_upload',
--     data JSONB,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE INDEX idx_notifications_created_at ON notifications(created_at);

-- -- =====================================================
-- -- 10. scheduler_meta table (tracks last run of the document upload check)
-- -- =====================================================
-- CREATE TABLE scheduler_meta (
--     key VARCHAR(50) PRIMARY KEY,
--     last_run TIMESTAMPTZ NOT NULL
-- );

-- -- Initialize with a starting point (e.g., 5 hours ago so the first run catches recent uploads)
-- INSERT INTO scheduler_meta (key, last_run) 
-- VALUES ('document_upload_check', NOW() - INTERVAL '5 hours');

-- -- 1. Make batch nullable
-- ALTER TABLE users ALTER COLUMN batch DROP NOT NULL;

-- -- 2. Add the check constraint only if it doesn't exist
-- DO $$
-- BEGIN
--   IF NOT EXISTS (
--     SELECT 1 FROM pg_constraint 
--     WHERE conname = 'users_batch_check' AND conrelid = 'users'::regclass
--   ) THEN
--     ALTER TABLE users ADD CONSTRAINT users_batch_check
--     CHECK (
--       (role = 'recruiter' AND batch IS NULL) OR
--       (role = 'candidate' AND batch IS NOT NULL AND batch BETWEEN 1900 AND 2100)
--     );
--   END IF;
-- END $$;

-- ALTER TABLE dox 
-- ADD COLUMN medical_upload_allowed BOOLEAN NOT NULL DEFAULT TRUE,
-- ADD COLUMN police_upload_allowed BOOLEAN NOT NULL DEFAULT TRUE;

-- ALTER TABLE dox DROP COLUMN upload_allowed;

-- SELECT tablename
-- FROM pg_tables
-- WHERE schemaname = 'public';

-- -- Insert a recruiter user (will get employee_id = 1)
-- INSERT INTO users (first_name, last_name, email, ph_no, batch, role, status)
-- VALUES ('Admin', 'User', 'admin@example.com', '1234567890', 2026, 'recruiter', 1);

-- -- Insert first_login record for the recruiter (use the employee_id from the insert)
-- INSERT INTO first_login (user_id, otp, valid_until, new)
-- VALUES (1, '123456', NOW() + INTERVAL '1 day', true);

-- ALTER TABLE auth ADD COLUMN locked_until TIMESTAMPTZ;

-- CREATE TABLE IF NOT EXISTS token_blacklist (
--     jti UUID PRIMARY KEY,
--     expires_at TIMESTAMPTZ NOT NULL,
--     created_at TIMESTAMPTZ DEFAULT NOW()
-- );

-- CREATE INDEX IF NOT EXISTS idx_token_blacklist_expires_at ON token_blacklist(expires_at);

-- ALTER TABLE dox ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();


select * from users;

